services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: local
    
    container_name: quiz_service

    networks:
      - php_network

    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor

  webserver:
    image: nginx:alpine
    container_name: quiz_nginx
    
    networks:
      - php_network
      # - services_network

    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    
    depends_on:
      - app

networks:
  php_network:
    driver: bridge