include:
  - ./frontend_app/docker-compose.yml
  - ./api_gateway/docker-compose.yml
  # - ./auth_service/docker-compose.prod.yml
  # - ./quiz_service/docker-compose.prod.yml
  # - ./analytics_service/docker-compose.prod.yml
  # - ./study_experience_service/docker-compose.prod.yml

services:
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik_reverse_proxy"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - services_network

networks:
  services_network:
    driver: bridge