# Working directory for Air
root = "."
tmp_dir = "/tmp"

[build]
cmd = "go build -o /tmp/main ."
bin = "/tmp/main"
# Command to run (here just running the compiled binary; prepend env vars if needed)
# full_bin = "APP_ENV=dev /tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp", ".git", "migrations"]
delay = 1000
stop_on_error = true

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true