services:
  auth_service:
    build:
      target: dev

    container_name: auth_service

    # networks:
    #   - services_network

    ports:
      - 80:80 # Use this port for local development without the traefik proxy
      - 5005:5005 # Debug port

    volumes:
      - .:/app
      - gradle_cache:/home/gradle/.gradle

volumes:
  gradle_cache: 